server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Ye line magic hai: ye .html apne aap check karegi
        try_files $uri $uri/ $uri.html /index.html;
    }

    # Courses folder ke liye special rule
    location /courses/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ $uri.html =404;
    }
}